build:
  nodes:
    php71:
      environment:
        php:
          version: 7.1
    php72:
      environment:
        php:
          version: 7.2
    php73:
      environment:
        php:
          version: 7.3
  tests:
    override:
      -
        command: 'bin/phpunit --coverage-clover=coverage_clover'
        coverage:
          file: 'coverage_clover'
          format: 'clover'
