language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer self-update
  - composer install

script:
  - bin/phpunit --coverage-clover=coverage.clover

notifications:
  email:
    - brulics@gmail.com

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
